In [1]:
import pickle
import utils as ut
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.model_selection import KFold

In [2]:
PATH = '../data/water_potability.csv'
label_column='Potability'
have_classes=True
drop_columns_list=['Id']
drop_columns=True

df, df_one_hot, X, y, classes, columns = ut.clean_data(PATH=PATH, shuffle=True, label_column=label_column, drop_columns_list=drop_columns_list, drop_columns=drop_columns, have_classes=have_classes, dropna=True)
df

ph    Hardness        Solids  Chloramines     Sulfate  \
1272  10.146290  242.151734  24649.674748     4.803373  347.069725   
357    7.459145  217.700130  19436.503542     4.639116  352.424439   
73     6.506488  202.285938  17087.076902     6.201983  326.662368   
355    6.032189  200.420756  32882.155943     6.516519  352.018638   
514    8.054886  200.943484  12642.065947     7.309822  334.442064   
...         ...         ...           ...          ...         ...   
982    6.539115  218.619699  23308.296877     7.177445  355.443831   
717    5.036454  190.164520  29258.738136     4.991061  300.475925   
367    8.576740  221.150258  24897.286602     6.222626  341.809210   
1846   4.633203  208.908036  29307.128945     6.125585  304.031776   
1649   6.089431  207.267133  11339.166055     8.888347  317.279123   

      Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
1272    348.484039       17.614799        73.001545   4.481552           0  
357     494.094339       14.460295        57.196188   3.841052           0  
73      481.771934       16.535186        46.205748   3.548776           0  
355     349.982173       14.104821        43.376808   3.423832           0  
514     446.748442       14.949080        71.202038   3.514098           0  
...            ...             ...              ...        ...         ...  
982     585.166427       10.742146        40.773856   4.211672           1  
717     332.359715       11.055801       116.161622   3.534665           1  
367     389.292785       15.952132        36.082583   3.916115           0  
1846    456.214828       10.817158       111.115310   4.751859           0  
1649    531.768988       11.674318        48.358250   4.366861           0  

[2011 rows x 10 columns]

In [3]:
pickle_in = open('historico/historico5x-no-validate-pickle.pickle',"rb")
data = pickle.load(pickle_in)

In [4]:
def sort_func(item):
    return item[1]
print(data[0])
data = data[1:-1]
data.sort(key=sort_func, reverse=True)
data

['loss', 'acc', 'learning_rate', 'momentum']


[[0.28170503973960875, 0.9949278950691223, 0.01, 0.36],
 [0.23264294266700744, 0.9923421144485474, 0.01, 0.16],
 [0.25377528071403505, 0.991745400428772, 0.01, 0.26],
 [0.27415605783462527, 0.9916459441184997, 0.01, 0.31],
 [0.3456865906715393, 0.9914470434188842, 0.01, 0.51],
 [0.2476332813501358, 0.9909497737884522, 0.01, 0.21],
 [0.3276894807815552, 0.9907508611679077, 0.01, 0.46],
 [0.3051791965961456, 0.9896568894386292, 0.01, 0.41],
 [0.3648068308830261, 0.987468934059143, 0.01, 0.56],
 [0.3889909446239471, 0.9871705770492554, 0.01, 0.61],
 [0.24908385574817657, 0.9863749504089355, 0.01, 0.06],
 [0.4232665359973907, 0.9818995594978333, 0.01, 0.66],
 [0.25232577323913574, 0.9812033772468567, 0.01, 0.11],
 [0.5077038526535034, 0.9753356456756592, 0.01, 0.76],
 [0.8966486841440201, 0.973545503616333, 0.01, 0.01],
 [0.4724881112575531, 0.973545503616333, 0.01, 0.71],
 [0.5710028529167175, 0.959622073173523, 0.01, 0.81],
 [0.6526341676712036, 0.9307807087898254, 0.01, 0.86],
 [0.66039

In [5]:
y = [1,2, 3,4, 5,6, 7,8, 9,10]
y = np.array(y)
X = [1,2 ,3,4, 5,6, 7,8, 9,10]
X = np.array(X)
kf = KFold(n_splits=5)
print(kf.split(X, y))

<generator object _BaseKFold.split at 0x7fb8ed6d6f90>


In [6]:
def cross_validate(split_size, X_all, y_all):

    kf = KFold(n_splits=split_size)
    
    for train_idx, val_idx in kf.split(X_all, y_all):
        
        train_x = X_all[train_idx]
        train_y = y_all[train_idx]
        val_x = X_all[val_idx]
        val_y = y_all[val_idx]
        print(train_x, train_y)
        print('---')
        print(val_x, val_y)
        print('*****')
        print('*****')

In [7]:
cross_validate(2, X, y)

[ 6  7  8  9 10] [ 6  7  8  9 10]
---
[1 2 3 4 5] [1 2 3 4 5]
*****
*****
[1 2 3 4 5] [1 2 3 4 5]
---
[ 6  7  8  9 10] [ 6  7  8  9 10]
*****
*****


In [8]:
import numpy as np
from sklearn.model_selection import KFold
y = [1,2, 3,4, 5,6, 7,8, 9,10]
y = np.array(y)

X = [[1,1],[2,2] ,[3,3],[4,4], [5,5],[6,6], [7,7],[8,8], [9,9],[10,10]]
X = np.array(X)

kf = KFold(n_splits=2)
kf.get_n_splits(X)

print(kf)

for train_index, test_index in kf.split(X):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print()
    print(f'Treino - X: {X_train}  y: {y_train}')
    print('------------------------------------')
    print(f'Teste  - X: {X_test}   y: {y_test}')
    print()
    print('************************************')
    print('************************************')
    print()

KFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [5 6 7 8 9] TEST: [0 1 2 3 4]

Treino - X: [[ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]]  y: [ 6  7  8  9 10]
------------------------------------
Teste  - X: [[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]   y: [1 2 3 4 5]

************************************
************************************

TRAIN: [0 1 2 3 4] TEST: [5 6 7 8 9]

Treino - X: [[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]  y: [1 2 3 4 5]
------------------------------------
Teste  - X: [[ 6  6]
 [ 7  7]
 [ 8  8]
 [ 9  9]
 [10 10]]   y: [ 6  7  8  9 10]

************************************
************************************



In [9]:
from prettytable import PrettyTable
from prettytable import MSWORD_FRIENDLY, DEFAULT
#, MARKDOWN, ORGMODE,DEFAULT



table = PrettyTable( ['A','B','C'] )
table.set_style(DEFAULT)
#table.set_style(MSWORD_FRIENDLY)

table.add_row( [1,2,3] )
table.add_row( [1,2,3] )
table.add_row( [1,2,3] )
print(table)

+---+---+---+
| A | B | C |
+---+---+---+
| 1 | 2 | 3 |
| 1 | 2 | 3 |
| 1 | 2 | 3 |
+---+---+---+
